spring:
  profiles:
    active: EN,cat,dev
guru:
  name: ymlSuperuser
  password: ymlDBPassword
  jdbcurl: ymlSomeUrlforDB

---
spring:
  profiles: prod
guru:
  name: ymlProdSuperuser
  password: ymlProdDBPassword
  jdbcurl: ymlProdSomeUrlforDB